[package]
name = "chunked_transfer"
version = "1.5.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/frewsxcv/rust-chunked-transfer"
description = "Encoder and decoder for HTTP chunked transfer coding (RFC 7230 ยง 4.1)"
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "encode"
harness = false
